//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiectBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class importStiri
    {
        public int is_id { get; set; }
        public string is_titlu { get; set; }
        public string is_categorie { get; set; }
        public string is_autor { get; set; }
        public string is_data { get; set; }
    }
}
